---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - [private_network, ip: 33.33.33.10]

suites:
  - name: knockd
    run_list:
      - recipe[monit::default]
      - recipe[fake::default]
    attributes:
      monit:
        poll_period: 30
        poll_start_delay: 0
      knockd:
        interface: eth1
