---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - [private_network, ip: 33.33.33.10]
    attributes:
      dev_knock_ip: 33.33.33.10

  - name: ubuntu-14.04
    driver_config:
      network:
      - [private_network, ip: 33.33.33.11]
    attributes:
      dev_knock_ip: 33.33.33.11

  - name: debian-7.4
    driver_config:
      network:
      - [private_network, ip: 33.33.33.12]
    attributes:
      dev_knock_ip: 33.33.33.12


suites:
  - name: knockd
    run_list:
      - recipe[fake::default]
    attributes:
      monit:
        poll_period: 30
        poll_start_delay: 0
      knockd:
        interface: eth1
