AllCops:
  Exclude:
    - 'Guardfile'
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'providers/profile.rb'
    - 'definitions/sequence.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false
